### ISSUE TITLE
TStoreEvents gets lost

### ISSUE THREAD

**Issue by westner** [spinettaro/delphi-flux-seed#1]
Hello Mr. Spinetti,

we use you Flux-Framework with Delphi 10.3.3 under iOS, Android, Windows and Mac OS.

Here we do a FluxDispatch - the GUID is passed to identify their way through your framework.
09.07.2020 16:33:34: TdmMain.FluxDispatch: 19, 13404730, 67AEF47B-EA96-4524-A1E1-8629A89DAB1B
09.07.2020 16:33:34: TdmMain.FluxDispatch: 21, 13404730, 2921E5A3-BE8D-403F-9153-DAAEF616E742
09.07.2020 16:33:34: TdmMain.FluxDispatch: 20, 13404730, 5DDCD311-3C51-4466-B0F1-8D0BDFEC34E7

After the FluxDispatch the StoreChangeEvents and the .Render ist called

09.07.2020 16:33:37: TfrmDialogEditBase.OnStoreChange start, 2921E5A3-BE8D-403F-9153-DAAEF616E742
09.07.2020 16:33:37: TfrmDialogEditDocument.FluxRenderer: 21, 13404730, 2921E5A3-BE8D-403F-9153-DAAEF616E742
09.07.2020 16:33:37: TfamListBase.Render start, 2921E5A3-BE8D-403F-9153-DAAEF616E742
09.07.2020 16:33:38: TfamListBase.Render end, 2921E5A3-BE8D-403F-9153-DAAEF616E742
09.07.2020 16:33:38: TfrmDialogEditBase.OnStoreChange end, 2921E5A3-BE8D-403F-9153-DAAEF616E742
09.07.2020 16:33:38: TfrmDialogEditBase.OnStoreChange start, 67AEF47B-EA96-4524-A1E1-8629A89DAB1B
09.07.2020 16:33:38: TfrmDialogEditDocument.FluxRenderer: 19, 13404730, 67AEF47B-EA96-4524-A1E1-8629A89DAB1B
09.07.2020 16:33:38: TfrmDialogEditBase.Render start, 67AEF47B-EA96-4524-A1E1-8629A89DAB1B
09.07.2020 16:33:38: TfrmDialogEditBase.Render end, 67AEF47B-EA96-4524-A1E1-8629A89DAB1B
09.07.2020 16:33:38: TfrmDialogEditBase.OnStoreChange end, 67AEF47B-EA96-4524-A1E1-8629A89DAB1B
09.07.2020 16:33:38: TfrmDialogEditBase.OnStoreChange start, 5DDCD311-3C51-4466-B0F1-8D0BDFEC34E7
09.07.2020 16:33:38: TfrmDialogEditDocument.FluxRenderer: 20, 13404730, 5DDCD311-3C51-4466-B0F1-8D0BDFEC34E7
09.07.2020 16:33:38: TfamListBase.Render start, 5DDCD311-3C51-4466-B0F1-8D0BDFEC34E7
09.07.2020 16:33:38: TfamListBase.Render end, 5DDCD311-3C51-4466-B0F1-8D0BDFEC34E7
09.07.2020 16:33:38: TfrmDialogEditBase.OnStoreChange end, 5DDCD311-3C51-4466-B0F1-8D0BDFEC34E7

This works fine.

Now we call the FluxDispatch very fast several times. As you see in the log the .render is only called for the last three FluxDispatch-calls. all other calls get lost.

09.07.2020 16:33:55: TdmMain.FluxDispatch: 19, 215687, 2F361BE7-F33D-4DAF-848B-8CE602724813
09.07.2020 16:33:55: TdmMain.FluxDispatch: 21, 215687, 6D48C0B8-620F-4193-89E7-0DC9745183BC
09.07.2020 16:33:55: TdmMain.FluxDispatch: 20, 215687, E6C9D540-EBD5-43C2-AE9A-27825A984520
09.07.2020 16:33:55: TdmMain.FluxDispatch: 19, 215655, FB14AF6E-B408-4F55-8718-746536A9542A
09.07.2020 16:33:55: TdmMain.FluxDispatch: 21, 215655, 8BA4D1B0-2C7E-49AC-816E-DE99D7B0279A
09.07.2020 16:33:55: TdmMain.FluxDispatch: 20, 215655, 3F843E69-223B-44D6-A5D5-147373D9C51E
09.07.2020 16:33:55: TfrmDialogEditBase.OnStoreChange start, 2F361BE7-F33D-4DAF-848B-8CE602724813
09.07.2020 16:33:55: TfrmDialogEditBase.OnStoreChange start, 6D48C0B8-620F-4193-89E7-0DC9745183BC
09.07.2020 16:33:55: TdmMain.FluxDispatch: 19, 215073, D869A15C-3AE2-4459-AE6E-66FD6257F4B6
09.07.2020 16:33:55: TdmMain.FluxDispatch: 21, 215073, 93EF68E7-A57C-4049-A2DB-CA2E26CFBEE1
09.07.2020 16:33:55: TdmMain.FluxDispatch: 20, 215073, A6C0C075-7BA6-4F87-8A79-7D784A6DC55D
09.07.2020 16:33:55: TfrmDialogEditBase.OnStoreChange start, FB14AF6E-B408-4F55-8718-746536A9542A
09.07.2020 16:33:55: TdmMain.FluxDispatch: 19, 174351, DB5259FF-B64C-48B9-9A51-1D6329E20458
09.07.2020 16:33:56: TdmMain.FluxDispatch: 21, 174351, 441E467E-5276-47EE-B2F2-66A6BD44FF6E
09.07.2020 16:33:56: TdmMain.FluxDispatch: 20, 174351, F520273F-17A1-4E6C-970D-B67B7BD6182B
09.07.2020 16:33:56: TfrmDialogEditBase.OnStoreChange start, 3F843E69-223B-44D6-A5D5-147373D9C51E
09.07.2020 16:33:56: TfrmDialogEditBase.OnStoreChange start, D869A15C-3AE2-4459-AE6E-66FD6257F4B6
09.07.2020 16:33:56: TdmMain.FluxDispatch: 19, 154143, F5BE7C82-79EC-4FFF-9BA0-4A5F3F6F8FE9
09.07.2020 16:33:56: TdmMain.FluxDispatch: 21, 154143, F3B6D7E8-07C7-49FF-BBC8-A6C7C9942A33
09.07.2020 16:33:56: TdmMain.FluxDispatch: 20, 154143, B23D0096-4067-4F63-A8ED-3600554B66C8
09.07.2020 16:33:56: TdmMain.FluxDispatch: 19, 145337, 4AAB6730-D731-4996-87B2-9736F31A07D4
09.07.2020 16:33:56: TdmMain.FluxDispatch: 21, 145337, E5C1F18D-B7E0-4F95-AD97-DCCB6E494B5D
09.07.2020 16:33:56: TdmMain.FluxDispatch: 20, 145337, 1F583A5E-D85C-42EF-AD40-D1AC39286683
09.07.2020 16:33:56: TdmMain.FluxDispatch: 19, 92940, CF7532EB-868D-4FF6-8EFA-CB903E975D6C
09.07.2020 16:33:56: TdmMain.FluxDispatch: 21, 92940, 750B9E95-4057-49B9-9FA9-9E9D02E77C4E
09.07.2020 16:33:56: TdmMain.FluxDispatch: 20, 92940, F76E0EA4-8486-4556-800F-27A3356970F9
09.07.2020 16:33:56: TfrmDialogEditBase.OnStoreChange start, A6C0C075-7BA6-4F87-8A79-7D784A6DC55D
09.07.2020 16:33:56: TfrmDialogEditBase.OnStoreChange start, 8BA4D1B0-2C7E-49AC-816E-DE99D7B0279A
09.07.2020 16:33:56: TfrmDialogEditBase.OnStoreChange start, 93EF68E7-A57C-4049-A2DB-CA2E26CFBEE1
09.07.2020 16:33:56: TdmMain.FluxDispatch: 19, 154184, B5AB40F1-45E6-4DCC-A4C8-E4F5D2AD1C8F
09.07.2020 16:33:56: TdmMain.FluxDispatch: 21, 154184, CA97D83A-B91A-40A6-87CB-00A72B84EBE1
09.07.2020 16:33:56: TdmMain.FluxDispatch: 20, 154184, B6AA092B-7F47-42A4-950B-041B8FD0C915
09.07.2020 16:33:56: TfrmDialogEditBase.OnStoreChange start, DB5259FF-B64C-48B9-9A51-1D6329E20458
09.07.2020 16:33:56: TfrmDialogEditBase.OnStoreChange start, 441E467E-5276-47EE-B2F2-66A6BD44FF6E
09.07.2020 16:33:56: TfrmDialogEditBase.OnStoreChange start, F520273F-17A1-4E6C-970D-B67B7BD6182B
09.07.2020 16:33:56: TfrmDialogEditBase.OnStoreChange start, E6C9D540-EBD5-43C2-AE9A-27825A984520
09.07.2020 16:33:56: TfrmDialogEditBase.OnStoreChange start, F5BE7C82-79EC-4FFF-9BA0-4A5F3F6F8FE9
09.07.2020 16:33:56: TdmMain.FluxDispatch: 19, 64870, 06B420E0-B0F6-4E83-873D-1F295289D22B
09.07.2020 16:33:56: TdmMain.FluxDispatch: 21, 64870, 26119ADB-EFB2-4CC1-A9B3-C8E6F3465AF4
09.07.2020 16:33:56: TdmMain.FluxDispatch: 20, 64870, 0E97A4BA-0B04-49DC-BBBE-51B1608E4B21
09.07.2020 16:33:56: TfrmDialogEditBase.OnStoreChange start, B23D0096-4067-4F63-A8ED-3600554B66C8
09.07.2020 16:33:57: TfrmDialogEditBase.OnStoreChange start, E5C1F18D-B7E0-4F95-AD97-DCCB6E494B5D
09.07.2020 16:33:57: TdmMain.FluxDispatch: 19, 38600, D09CFFB3-DB10-46CA-9276-C7C10B69A902
09.07.2020 16:33:57: TdmMain.FluxDispatch: 21, 38600, 6CBBEB56-7B0D-4A9C-8F67-50E7F957E3E9
09.07.2020 16:33:57: TdmMain.FluxDispatch: 20, 38600, 45420F79-ECE0-4B9B-A972-99D7D0B5CDDE
09.07.2020 16:33:57: TdmMain.FluxDispatch: 19, 32119, 0281EE13-8407-4D85-AA37-6F224B0B932D
09.07.2020 16:33:57: TdmMain.FluxDispatch: 21, 32119, A193D7D8-4164-4D7C-B152-8502680C66E3
09.07.2020 16:33:57: TdmMain.FluxDispatch: 20, 32119, A11B578E-C7D3-45DB-A982-B343CE772EF8
09.07.2020 16:33:57: TdmMain.FluxDispatch: 19, 48426, 91BC499D-BE3E-4D43-8860-C9432CF8B825
09.07.2020 16:33:57: TdmMain.FluxDispatch: 21, 48426, D569AE4F-EED2-4F41-82F5-B717602AEA37
09.07.2020 16:33:57: TdmMain.FluxDispatch: 20, 48426, 0977396A-BCFC-4F5E-ABCF-C5C337B72DE2
09.07.2020 16:33:57: TdmMain.FluxDispatch: 19, 13404730, B6AB08F3-0DE8-4018-9742-57B1C9AA42ED
09.07.2020 16:33:57: TdmMain.FluxDispatch: 21, 13404730, 322A6CFF-51CC-401A-B01E-29CACE35C564
09.07.2020 16:33:57: TdmMain.FluxDispatch: 20, 13404730, 4EBF7DB1-A4B1-45C2-BC09-C7232DB519F4
09.07.2020 16:33:57: TdmMain.FluxDispatch: 19, 3485413, ACBA01C7-6785-4F15-8702-820908B36364
09.07.2020 16:33:57: TdmMain.FluxDispatch: 21, 3485413, 5259CC4F-BA6B-4C6B-B0C1-5127AD4989DA
09.07.2020 16:33:57: TdmMain.FluxDispatch: 20, 3485413, A0BC6356-8715-4D01-A9C8-1FADC7E372BF
09.07.2020 16:33:57: TfrmDialogEditBase.OnStoreChange start, F3B6D7E8-07C7-49FF-BBC8-A6C7C9942A33
09.07.2020 16:33:57: TfrmDialogEditBase.OnStoreChange start, 1F583A5E-D85C-42EF-AD40-D1AC39286683
09.07.2020 16:33:57: TfrmDialogEditBase.OnStoreChange start, 4AAB6730-D731-4996-87B2-9736F31A07D4
09.07.2020 16:33:57: TfrmDialogEditBase.OnStoreChange start, CF7532EB-868D-4FF6-8EFA-CB903E975D6C
09.07.2020 16:33:57: TdmMain.FluxDispatch: 19, 1563082, BA2ACFCB-3E11-4249-911D-0A00B355B714
09.07.2020 16:33:57: TdmMain.FluxDispatch: 21, 1563082, A6BD7EDA-BE31-45CE-9F20-2946D7F36ED4
09.07.2020 16:33:57: TdmMain.FluxDispatch: 20, 1563082, C1874188-D300-4A31-B519-69EC53F0FBEB
09.07.2020 16:33:57: TfrmDialogEditBase.OnStoreChange start, 750B9E95-4057-49B9-9FA9-9E9D02E77C4E
09.07.2020 16:33:57: TdmMain.FluxDispatch: 19, 1561986, 6246B8C8-7BF0-431D-AC7F-E1C149D2D163
09.07.2020 16:33:57: TdmMain.FluxDispatch: 21, 1561986, E322BE5E-24BB-4994-980F-7C720DB80A2E
09.07.2020 16:33:57: TdmMain.FluxDispatch: 20, 1561986, C2891210-965B-4E49-8759-2B69E52386A7
09.07.2020 16:33:57: TfrmDialogEditBase.OnStoreChange start, F76E0EA4-8486-4556-800F-27A3356970F9
09.07.2020 16:33:58: TdmMain.FluxDispatch: 19, 215687, A95233EF-8110-4A73-8AF7-7A61CF4AE436
09.07.2020 16:33:58: TdmMain.FluxDispatch: 21, 215687, 2A7D4922-C235-46B1-9414-44127730B099
09.07.2020 16:33:58: TdmMain.FluxDispatch: 20, 215687, 1AA19E77-8FF5-4FCA-9851-F4D0765296D5
09.07.2020 16:33:58: TfrmDialogEditBase.OnStoreChange start, B6AA092B-7F47-42A4-950B-041B8FD0C915
09.07.2020 16:33:58: TdmMain.FluxDispatch: 19, 215655, 7C53CAE8-7206-486E-80BA-4B2BBC6CFB11
09.07.2020 16:33:58: TdmMain.FluxDispatch: 21, 215655, 079DB5B0-5567-480B-9C3B-CE665756F2A2
09.07.2020 16:33:58: TdmMain.FluxDispatch: 20, 215655, 680F395A-943A-458D-B741-EBDE573F09EC
09.07.2020 16:33:58: TdmMain.FluxDispatch: 19, 215073, 1BF7B9DF-4856-4BFD-92FD-11F354F8D3F0
09.07.2020 16:33:58: TdmMain.FluxDispatch: 21, 215073, 87AB7CB4-35B4-47D0-A6EF-4C8019CB1E5F
09.07.2020 16:33:58: TdmMain.FluxDispatch: 20, 215073, 867779E5-69D8-45A9-94E2-DCF8E6DE4378
09.07.2020 16:33:58: TfrmDialogEditBase.OnStoreChange start, CA97D83A-B91A-40A6-87CB-00A72B84EBE1
09.07.2020 16:33:58: TfrmDialogEditBase.OnStoreChange start, 26119ADB-EFB2-4CC1-A9B3-C8E6F3465AF4
09.07.2020 16:33:58: TfrmDialogEditBase.OnStoreChange start, 06B420E0-B0F6-4E83-873D-1F295289D22B
09.07.2020 16:33:58: TfrmDialogEditBase.OnStoreChange start, 6CBBEB56-7B0D-4A9C-8F67-50E7F957E3E9
09.07.2020 16:33:58: TfrmDialogEditBase.OnStoreChange start, 45420F79-ECE0-4B9B-A972-99D7D0B5CDDE
09.07.2020 16:33:58: TfrmDialogEditBase.OnStoreChange start, 0281EE13-8407-4D85-AA37-6F224B0B932D
09.07.2020 16:33:58: TfrmDialogEditBase.OnStoreChange start, B5AB40F1-45E6-4DCC-A4C8-E4F5D2AD1C8F
09.07.2020 16:33:58: TfrmDialogEditBase.OnStoreChange start, A193D7D8-4164-4D7C-B152-8502680C66E3
09.07.2020 16:33:58: TfrmDialogEditBase.OnStoreChange start, A11B578E-C7D3-45DB-A982-B343CE772EF8
09.07.2020 16:33:59: TfrmDialogEditBase.OnStoreChange start, D569AE4F-EED2-4F41-82F5-B717602AEA37
09.07.2020 16:33:59: TfrmDialogEditBase.OnStoreChange start, D09CFFB3-DB10-46CA-9276-C7C10B69A902
09.07.2020 16:33:59: TfrmDialogEditBase.OnStoreChange start, 91BC499D-BE3E-4D43-8860-C9432CF8B825
09.07.2020 16:33:59: TfrmDialogEditBase.OnStoreChange start, 0977396A-BCFC-4F5E-ABCF-C5C337B72DE2
09.07.2020 16:33:59: TfrmDialogEditBase.OnStoreChange start, 322A6CFF-51CC-401A-B01E-29CACE35C564
09.07.2020 16:33:59: TfrmDialogEditBase.OnStoreChange start, ACBA01C7-6785-4F15-8702-820908B36364
09.07.2020 16:33:59: TfrmDialogEditBase.OnStoreChange start, 4EBF7DB1-A4B1-45C2-BC09-C7232DB519F4
09.07.2020 16:33:59: TfrmDialogEditBase.OnStoreChange start, 0E97A4BA-0B04-49DC-BBBE-51B1608E4B21
09.07.2020 16:33:59: TfrmDialogEditBase.OnStoreChange start, BA2ACFCB-3E11-4249-911D-0A00B355B714
09.07.2020 16:34:00: TfrmDialogEditBase.OnStoreChange start, 5259CC4F-BA6B-4C6B-B0C1-5127AD4989DA
09.07.2020 16:34:00: TfrmDialogEditBase.OnStoreChange start, A6BD7EDA-BE31-45CE-9F20-2946D7F36ED4
09.07.2020 16:34:00: TfrmDialogEditBase.OnStoreChange start, B6AB08F3-0DE8-4018-9742-57B1C9AA42ED
09.07.2020 16:34:00: TfrmDialogEditBase.OnStoreChange start, A0BC6356-8715-4D01-A9C8-1FADC7E372BF
09.07.2020 16:34:00: TfrmDialogEditBase.OnStoreChange start, C1874188-D300-4A31-B519-69EC53F0FBEB
09.07.2020 16:34:00: TfrmDialogEditBase.OnStoreChange start, 6246B8C8-7BF0-431D-AC7F-E1C149D2D163
09.07.2020 16:34:00: TfrmDialogEditBase.OnStoreChange start, 2A7D4922-C235-46B1-9414-44127730B099
09.07.2020 16:34:00: TfrmDialogEditBase.OnStoreChange start, A95233EF-8110-4A73-8AF7-7A61CF4AE436
09.07.2020 16:34:00: TfrmDialogEditBase.OnStoreChange start, 1AA19E77-8FF5-4FCA-9851-F4D0765296D5
09.07.2020 16:34:00: TfrmDialogEditBase.OnStoreChange start, 7C53CAE8-7206-486E-80BA-4B2BBC6CFB11
09.07.2020 16:34:00: TfrmDialogEditBase.OnStoreChange start, 079DB5B0-5567-480B-9C3B-CE665756F2A2
09.07.2020 16:34:00: TfrmDialogEditBase.OnStoreChange start, 680F395A-943A-458D-B741-EBDE573F09EC
09.07.2020 16:34:01: TfrmDialogEditBase.OnStoreChange start, C2891210-965B-4E49-8759-2B69E52386A7
09.07.2020 16:34:01: TfrmDialogEditBase.OnStoreChange start, 87AB7CB4-35B4-47D0-A6EF-4C8019CB1E5F
09.07.2020 16:34:01: TfrmDialogEditDocument.FluxRenderer: 21, 215073, 87AB7CB4-35B4-47D0-A6EF-4C8019CB1E5F
09.07.2020 16:34:01: TfamListBase.Render start, 87AB7CB4-35B4-47D0-A6EF-4C8019CB1E5F
09.07.2020 16:34:01: TfamListBase.Render end, 87AB7CB4-35B4-47D0-A6EF-4C8019CB1E5F
09.07.2020 16:34:01: TfrmDialogEditBase.OnStoreChange end, 87AB7CB4-35B4-47D0-A6EF-4C8019CB1E5F
09.07.2020 16:34:01: TfrmDialogEditBase.OnStoreChange start, 1BF7B9DF-4856-4BFD-92FD-11F354F8D3F0
09.07.2020 16:34:01: TfrmDialogEditDocument.FluxRenderer: 19, 215073, 1BF7B9DF-4856-4BFD-92FD-11F354F8D3F0
09.07.2020 16:34:01: TfrmDialogEditBase.Render start, 1BF7B9DF-4856-4BFD-92FD-11F354F8D3F0
09.07.2020 16:34:01: TfrmDialogEditBase.Render end, 1BF7B9DF-4856-4BFD-92FD-11F354F8D3F0
09.07.2020 16:34:01: TfrmDialogEditBase.OnStoreChange end, 1BF7B9DF-4856-4BFD-92FD-11F354F8D3F0
09.07.2020 16:34:01: TfrmDialogEditBase.OnStoreChange start, 867779E5-69D8-45A9-94E2-DCF8E6DE4378
09.07.2020 16:34:01: TfrmDialogEditDocument.FluxRenderer: 20, 215073, 867779E5-69D8-45A9-94E2-DCF8E6DE4378
09.07.2020 16:34:01: TfamListBase.Render start, 867779E5-69D8-45A9-94E2-DCF8E6DE4378
09.07.2020 16:34:01: TfamListBase.Render end, 867779E5-69D8-45A9-94E2-DCF8E6DE4378
09.07.2020 16:34:01: TfrmDialogEditBase.OnStoreChange end, 867779E5-69D8-45A9-94E2-DCF8E6DE4378
09.07.2020 16:34:01: TfrmDialogEditBase.OnStoreChange start, E322BE5E-24BB-4994-980F-7C720DB80A2E

Why?

If we now call three FluxDispatch slowly then all is working fine again.

09.07.2020 16:34:09: TdmMain.FluxDispatch: 19, 215073, 7AD04F8D-0D96-487E-A09B-8C8BF72AB1AA
09.07.2020 16:34:09: TdmMain.FluxDispatch: 21, 215073, 31CC8ED8-6818-41BF-AF85-38267A38BF92
09.07.2020 16:34:09: TdmMain.FluxDispatch: 20, 215073, B758CF6D-2EB4-42C4-9CA1-317447BF4143
09.07.2020 16:34:09: TfrmDialogEditBase.OnStoreChange start, 7AD04F8D-0D96-487E-A09B-8C8BF72AB1AA
09.07.2020 16:34:09: TfrmDialogEditDocument.FluxRenderer: 19, 215073, 7AD04F8D-0D96-487E-A09B-8C8BF72AB1AA
09.07.2020 16:34:09: TfrmDialogEditBase.Render start, 7AD04F8D-0D96-487E-A09B-8C8BF72AB1AA
09.07.2020 16:34:09: TfrmDialogEditBase.Render end, 7AD04F8D-0D96-487E-A09B-8C8BF72AB1AA
09.07.2020 16:34:09: TfrmDialogEditBase.OnStoreChange end, 7AD04F8D-0D96-487E-A09B-8C8BF72AB1AA
09.07.2020 16:34:09: TfrmDialogEditBase.OnStoreChange start, 31CC8ED8-6818-41BF-AF85-38267A38BF92
09.07.2020 16:34:09: TfrmDialogEditDocument.FluxRenderer: 21, 215073, 31CC8ED8-6818-41BF-AF85-38267A38BF92
09.07.2020 16:34:09: TfamListBase.Render start, 31CC8ED8-6818-41BF-AF85-38267A38BF92
09.07.2020 16:34:10: TfamListBase.Render end, 31CC8ED8-6818-41BF-AF85-38267A38BF92
09.07.2020 16:34:10: TfrmDialogEditBase.OnStoreChange end, 31CC8ED8-6818-41BF-AF85-38267A38BF92
09.07.2020 16:34:10: TfrmDialogEditBase.OnStoreChange start, B758CF6D-2EB4-42C4-9CA1-317447BF4143
09.07.2020 16:34:10: TfrmDialogEditDocument.FluxRenderer: 20, 215073, B758CF6D-2EB4-42C4-9CA1-317447BF4143
09.07.2020 16:34:10: TfamListBase.Render start, B758CF6D-2EB4-42C4-9CA1-317447BF4143
09.07.2020 16:34:10: TfamListBase.Render end, B758CF6D-2EB4-42C4-9CA1-317447BF4143
09.07.2020 16:34:10: TfrmDialogEditBase.OnStoreChange end, B758CF6D-2EB4-42C4-9CA1-317447BF4143

How swallows or render-calls or is this by design?

Greetings

Stefan

**Comment by spinettaro** [comment]
Hi @westner . Could you provide a little demo that highlights the issue? 
Otherwise it's really hard to help you

**Comment by EpoUnlimited** [comment]
Hi Daniel,
Very interesting but may be a good idea to update for Delphi 11 (and DEB 2.0)
And too thenks for your excellent books;
Eddy

**Comment by spinettaro** [comment]
closing
